[platformio]
default_envs = uno_r4_wifi

[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
monitor_speed = 115200

lib_deps =
    waspinator/AccelStepper@^1.64
    adafruit/Adafruit GFX Library@^1.12.6
    adafruit/Adafruit SSD1306@^2.5.17

build_flags =
    -Wall
    -Wextra
    -Wpedantic
    -DSSD1306_NO_SPLASH
