[platformio]
default_envs = uno_r4_wifi
src_dir = arduino/WheelWrecker

[env:uno_r4_wifi]
platform = renesas-ra@1.9.0
board = uno_r4_wifi
framework = arduino
monitor_speed = 115200

lib_deps =
    waspinator/AccelStepper@1.64
    adafruit/Adafruit BusIO@1.17.4
    adafruit/Adafruit GFX Library@1.12.6
    adafruit/Adafruit SSD1306@2.5.17

build_flags =
    -Wall
    -Wextra
    -Wpedantic
